name: Nix CI

on:
  push:
    branches: [main, master]
    paths:
      - "flake.nix"
      - "flake.lock"
      - "**.nix"
      - "**.sh"
      - ".github/workflows/**.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "flake.nix"
      - "flake.lock"
      - "**.nix"
      - "**.sh"
      - ".github/workflows/**.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: hoshinoaya
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Check flake
        run: nix flake check

      - name: Show flake info
        run: nix flake show

  build:
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        package:
          [
            qemu-bap,
            rizin,
            binutils-h8500,
            gcc-toolchain-tricore,
            gdb-tricore,
            h8300-elf-toolchain,
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NIX_FIRST_BUILD_UID: "700"

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: hoshinoaya
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ${{ matrix.package }}
        run: nix build .#${{ matrix.package }} -L

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: |
          nix fmt -- --ci .
